// TRINITY NEURAL CORE V12 - OMEGA ULTIMATE DATABASE
export interface Stock {
  symbol: string;
  price: number;
  change: number;
  chgPct: number; 
  high: number;
  low: number;
  rFac: string; 
  sign: 'bullish' | 'bearish' | 'neutral';
}

export interface Sector {
  id: string;
  name: string;
  status: 'bullish' | 'bearish' | 'neutral';
  upCount: number;
  downCount: number;
  totalCount: number;
  multiplier: string;
  velocity: number;
  stocks: Stock[];
}

export const SECTORS_LIST = [
  "IT", "NIFTY MID SELECT", "FMCG", "NIFTY 50", "SENSEX", "AUTO", "REALTY", "PVT BANK", "METAL", "BANK", "CEMENT", "PSU BANK", "FIN SERVICE", "ENERGY", "PHARMA"
];

// Normalized & Verified F&O Stocks (Zero Duplicates within sectors)
export const STOCKS_BY_SECTOR: Record<string, string[]> = {
  "IT": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "LTIM", "PERSISTENT", "COFORGE", "MPHASIS", "TATAELXSI", "OFSS", "KPITTECH", "CYIENT", "KAYNES", "TATATECH", "BSOFT", "LTTS", "MASTEK", "SONATSOFTW", "ZENSARTECH"],
  "NIFTY MID SELECT": ["IDFCFIRSTB", "AUBANK", "CUMMINSIND", "FEDERALBNK", "GODREJPROP", "INDIANB", "LUPIN", "M&MFIN", "MAXHEALTH", "POLYCAB", "RECLTD", "VOLTAS", "TATACOMM", "ESCORTS", "BALKRISIND", "CONCOR", "DIXON", "GLENMARK", "INDIAMART", "PAGEIND", "TATACHEM", "ZEEL", "PETRONET", "JUBLFOOD", "GUJGASLTD", "MFSL", "ABCAPITAL", "PEL"],
  "FMCG": ["ITC", "HINDUNILVR", "NESTLEIND", "BRITANNIA", "GODREJCP", "MARICO", "DABUR", "COLPAL", "UNITDSPR", "EMAMILTD", "JYOTHYLAB", "BALRAMCHIN", "DALMIASUG", "GODFRYPHLP", "UBL", "RADICO", "VBL", "TATACONSUM", "PVRINOX", "DEVYANI", "SAPPHIRE"],
  "NIFTY 50": ["ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE", "BEL", "BHARTIARTL", "BPCL", "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY", "ITC", "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LT", "LTIM", "M&M", "MARUTI", "NESTLEIND", "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SBIN", "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TCS", "TECHM", "TITAN", "ULTRACEMCO", "UPL", "WIPRO"],
  "SENSEX": ["RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK", "LT", "AXISBANK", "ASIANPAINT", "SUNPHARMA", "TITAN", "ULTRACEMCO", "BAJFINANCE", "M&M", "MARUTI", "TATASTEEL", "JSWSTEEL", "POWERGRID", "NTPC", "HCLTECH", "WIPRO", "TECHM", "NESTLEIND", "TATAMOTORS", "INDUSINDBK", "BAJAJ-AUTO"],
  "AUTO": ["MARUTI", "TATAMOTORS", "M&M", "EICHERMOT", "BAJAJ-AUTO", "HEROMOTOCO", "TVSMOTOR", "ASHOKLEY", "HYUNDAI", "FORCEMOT", "MRF", "APOLLOTYRE", "BALKRISIND", "JKTYRE", "CEATLTD", "BOSCHLTD", "MOTHERSON", "SONACOMS", "TIINDIA", "EXIDEIND", "ARE_M", "BHARATFORG", "SAMVARDHANA", "TUBACEX"],
  "REALTY": ["DLF", "GODREJPROP", "OBEROIRLTY", "LODHA", "PRESTIGE", "PHOENIXLTD", "BRIGADE", "MAHLIFE", "SUNTECK", "MACPROTECH", "SOBHA", "IBREALEST"],
  "PVT BANK": ["HDFCBANK", "ICICIBANK", "AXISBANK", "KOTAKBANK", "INDUSINDBK", "FEDERALBNK", "IDFCFIRSTB", "BANDHANBNK", "RBLBANK", "CITYUNIONBK", "CUB", "IDBI", "KARURVYSYA", "CSBBANK", "SOUTHBANK", "YESBANK"],
  "METAL": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL", "NATIONALUM", "SAIL", "NMDC", "JINDALSTEL", "JSL", "APLLTD", "HINDZINC", "RATNAMANI", "WELCORP"],
  "BANK": ["HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK", "BANKBARODA", "INDUSINDBK", "CANBK", "PNB", "AUBANK", "BANDHANBNK", "SOUTHBANK", "YESBANK", "PSB"],
  "CEMENT": ["ULTRACEMCO", "GRASIM", "AMBUJACEM", "ACC", "JKCEMENT", "DALBHARAT", "SHREECEM", "RAMCOCEM", "INDIACEM", "HEIDELBERG", "ORIENTCEM", "SAGCEM"],
  "PSU BANK": ["SBIN", "BANKBARODA", "CANBK", "PNB", "UNIONBANK", "INDIANB", "BANKINDIA", "MAHABANK", "IOB", "UCOBANK", "PSB", "CENTRALBK"],
  "FIN SERVICE": ["BAJFINANCE", "BAJAJFINSV", "SHRIRAMFIN", "CHOLAFIN", "M&MFIN", "MUTHOOTFIN", "MANAPPURAM", "LTF", "POONAWALLA", "ABCAPITAL", "PEL", "LICHSGFIN", "CANFINHOME", "JIOFIN", "ANGELONE", "BSE", "CAMS", "CDSL", "MCX", "NUVAMA", "360ONE", "KFINTECH", "MOTILALOFS", "IBULHSGFIN", "LICI", "SBILIFE", "HDFCLIFE", "ICICIPRULI", "ICICIGI", "STARHEALTH", "HUDCO", "IRFC", "GICRE", "IDFC", "IFCI"],
  "ENERGY": ["NTPC", "POWERGRID", "TATAPOWER", "JSWENERGY", "ADANIPOWER", "ADANIGREEN", "ADANIENSOL", "NHPC", "SJVN", "NLCINDIA", "CESC", "TORNTPOWER", "POWERINDIA", "PREMIERENE", "WAAREEENER", "SUZLON", "RELIANCE", "ONGC", "BPCL", "IOC", "HPCL", "GAIL", "OIL", "COALINDIA", "ATGL", "PETRONET"],
  "PHARMA": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "ZYDUSLIFE", "AUROPHARMA", "LUPIN", "ALKEM", "TORNTPHARM", "BIOCON", "GLENMARK", "IPCALAB", "LAURUSLABS", "GRANULES", "PPLPHARMA", "MANKIND", "ABBOTINDIA", "SYNGENE", "GLAND", "SANOFI", "APOLLOHOSP", "MAXHEALTH", "FORTIS", "LALPATHLAB", "METROPOLIS", "GLOBAL", "GULPOLY", "ERIS", "JBCHEPHARM"]
};

export function getSectorData(): Sector[] {
  return SECTORS_LIST.map(name => {
    const symbols = Array.from(new Set(STOCKS_BY_SECTOR[name] || []));
    const stocks: Stock[] = symbols.map((symbol) => ({
      symbol, price: 0, change: 0, chgPct: 0, high: 0, low: 0, rFac: "0.00x", sign: 'neutral'
    }));
    return { id: name.toLowerCase().replace(/ /g, '-'), name, status: 'neutral', upCount: 0, downCount: stocks.length, totalCount: stocks.length, multiplier: "0.00x", velocity: 0, stocks };
  });
}

export function isMarketOpen() { return false; }
